### PR TITLE
remove threadpool,colorama dependencies of setup.py script and db file

### PR DESCRIPTION
**Pull request by naihe2010**
I think the setup.py should be more and more simple and it should not depends too many modules.

### CODE REVIEW

**Comment by evi1m0** [comment]
Nice :)

**Comment by naihe2010** [comment]
Sorry!!!
I made a mistake. The hive.db should not be deleted.

**Comment by evi1m0** [comment]
got

**Comment by naihe2010** [comment]
maybe add a initdb script or init db action in setup.py is a more better idea.
or, create db and init db file when it not exists automatically when program start.

**Pull request merged**
